### PR TITLE
Scripts for performing differential analysis from Bcbio raw counts with edgeR

### PR DESCRIPTION
**Pull request by chrischen1**

### CODE REVIEW

**Comment by ArtemSokolov** [comment]
Thanks, Chris. It looks good. I only have a couple of comments:
1. You probably don't need to include your `.Rhistory` file.
2. Do you want to add a short paragraph to `README` giving a brief description of your scripts and showing an example usage?

**Comment by chrischen1** [comment]
Thanks Artem. I've added the .Rhistory into my .gitignore, and added some explanations in readme. Would you think it is necessary to also include some sample input files?

**Comment by chrischen1** [comment]
Add documentation for run_de.R in README.md

**Comment by ArtemSokolov** [comment]
Sample files might be nice, if they are not too large.

I think your new .gitignore wants to remove `sample_description.csv` and `yaml_example.yaml`. Your latest commits are dropping those two files.

**Comment by chrischen1** [comment]
Thanks Artem. Yes, I removed them in the latest commit since they are part of the "sample input" for the pipeline. If you think small sample files are OK to put here, I would re-add them as well as a some count table with group annotation.

**Comment by smkartik** [comment]
Hi Chris, I would move the run_de.R file under the examples folder

**Comment by ArtemSokolov** [comment]
Hi Chris,

Thanks for adding the examples. My concern for removing `sample_description.csv` and `yaml_example.yaml` is that the README heavily references them. There are several steps that walk the user through downloading those files and feeding them to the bcbio pipeline. If you have that functionality incorporated into the sample input, then the README needs to be updated to reflect that. Otherwise, it's going to be too confusing for the user(s).

**Comment by chrischen1** [comment]
Hi Artem,
Yes, I agree that those files would be necessary. I have added back them under /example/config.

**Pull request merged**
